### ISSUE TITLE
deleteAll methods can not delete over 25 items

### ISSUE THREAD

**Issue by qwe0001** [TakuKobayashi/NodeDynamoDBORM#4]
### OK

```
function testDelete()
{
  var ORM = require('node-dynamodb-orm');
  var DynamoDBORM = ORM.DynamoDBORM;

  DynamoDBORM.updateConfig({
    region          : process.env['AWS_DYNAMO_DB_REGION'],
    accessKeyId     : process.env['AWS_PUBLIC_KEY'],
    secretAccessKey : process.env['AWS_SECRET_KEY']
  });

  var model = new DynamoDBORM(process.env['AWS_DYNAMO_DB_MY_TABLE_NAME']);

  var arrObj =  [
    { num : 1  },
    { num : 2  },
    ...
    { num : 24 },
    { num : 25 } // OK
  ];

  model.deleteAll(arrObj);
}

testDelete(); // well done
```

### NG

```
function testDelete()
{
  ...

  var arrObj =  [
    { num : 1  },
    { num : 2  },
    ...
    { num : 24 },
    { num : 25 },
    { num : 26 }, // NG
  ];

  model.deleteAll(arrObj);
}

testDelete();
```

that returns exception like this.

```
'requestItems' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 25, Member must have length greater than or equal to 1]
```

More details are below

```
(node:7742) UnhandledPromiseRejectionWarning: ValidationException: 1 validation error detected: Value '{dataBroadCastAccessLogs=[WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=b1b6ce58-772f-4e88-a415-6ea22cd1d650, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=88ae30bd-4321-4c87-bb5d-45bb79a4bb82, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=c1ca40b0-9aff-46f4-aa34-103cecf4c7c6, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=2595b962-95db-480c-af2a-85fdd055ff6b, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=83b46d4d-22ff-4522-a589-7436658d9255, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=9aa74b80-862c-478a-a7d4-0fa3730325b6, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=be406254-14ef-4df0-a47b-81d4729533fc, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=aa241920-d610-46bd-bca3-c0f1063ac6ed, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=f5b664c1-322b-4205-a95a-b1e346a9b235, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=5ea5ff4f-a302-4dfc-b240-ef4fb39e0ae8, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=3b6b9669-3663-4bb1-8c8d-b0029e7b2580, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=48b2469f-1d63-4562-b38e-5722ccb44de7, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=a7d5c436-672f-4727-a226-d4e798ed64af, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=5ddf64cb-d0df-41cb-b405-284ec9692b45, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=544e3cfd-56f0-4250-aba3-c6235f9f5a56, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=d99d3b56-c9b3-4f35-be36-3616fc03e346, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=a0cc8f93-cd7b-4b53-9244-7b9b4bb29dc3, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=e3e4055c-b08f-4cc5-aca6-7ca9f84524a5, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=58d14c23-2587-49d5-b25f-c17a13b4a908, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=3a956440-a045-4b02-97f8-0fc5303dc59a, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=65f2fdd5-f06c-4e5b-bfe8-1c536633fb48, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=7933ffd7-0f84-492c-b26d-ab33c0f058ce, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=d4678c42-c234-4857-aaf7-1778b9f914a8, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=31cc9f55-bc68-4378-af0b-036b797c76cd, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=5e469fc4-b28c-45cb-9e1e-d28f970ee230, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)})), WriteRequest(putRequest=null, deleteRequest=DeleteRequest(key={log_id=AttributeValue(s=2ee4e3df-95a3-455e-aae9-e3ce3d78fab4, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)}))]}' at 'requestItems' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 25, Member must have length greater than or equal to 1]
    at Request.extractError (/home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/home/ec2-user/environment/myTestLambdaFunction/node_modules/aws-sdk/lib/event_listeners.js:307:13)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
```

### References

AWS Document says operation will reject if "There are more than 25 requests in the batch.".

https://docs.aws.amazon.com/cli/latest/reference/dynamodb/batch-write-item.html#batch-write-item

```
If one or more of the following is true, DynamoDB rejects the entire batch write operation:

・One or more tables specified in the BatchWriteItem request does not exist.
・Primary key attributes specified on an item in the request do not match those in the corresponding table's primary key schema.
・You try to perform multiple operations on the same item in the same BatchWriteItem request. ・For example, you cannot put and delete the same item in the same BatchWriteItem request.
・Your request contains at least two items with identical hash and range keys (which essentially is two put operations).
・There are more than 25 requests in the batch. <-- This is it!!
・Any individual item in a batch exceeds 400 KB.
・The total request size exceeds 16 MB.
```

### Runtime

AWS Lambda Node.js 10.x

aws-sdk@2.631.0
node-dynamodb-orm@0.1.3

### Other

Should I do NOT use deleteAll function and use ttl attribute?

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/time-to-live-ttl-how-to.html

**Comment by qwe0001** [comment]
I solved this problem on my way.

My method is to create a group of arrays every 25 and perform a delete operation for each group.

Like this. (worked on AWS Lambda)

```:index.js
async function getAll(model)
{
  return await model.all();
}

async function deleteAll(arrStr, model)
{
  var apiRequestMaxValue = 25;

  // example
  //var arrStr = [
  //  '88ae30bd-4321-4c87-bb5d-45bb79a4bb82',
  //  'c1ca40b0-9aff-46f4-aa34-103cecf4c7c6'
  //];

  // create array per 25 elements
  var targetArrays = _divideArray(arrStr, apiRequestMaxValue);

  for (var i = 0; i < targetArrays.length; i++) {
    var targetArr = targetArrays[i];
    await this._destroy(targetArr, model);
  }
}

function _divideArray(arr, num)
{
  var idx = 0;
  var results = new Array();
  var len = arr.length;

  while(idx + num < len){
    var result = arr.slice(idx, idx + num);
    results.push(result);
    idx = idx + num;
  }

  var rest = arr.slice(idx, len + 1);
  results.push(rest);

  return results;
}

async function _destroy(arrStr, model)
{
  // example
  //var arrStr = [
  //  '88ae30bd-4321-4c87-bb5d-45bb79a4bb82',
  //  'c1ca40b0-9aff-46f4-aa34-103cecf4c7c6'
  //];
  //var targetArr = [
  //  { log_id: '88ae30bd-4321-4c87-bb5d-45bb79a4bb82' },
  //  { log_id: 'c1ca40b0-9aff-46f4-aa34-103cecf4c7c6' }
  //];

  var primaryKey = "log_id";

  var targetArr = new Array();

  for(var i = 0; i < arrStr.length; i++){
    var targetObj = new Object();
    var logId = arrStr[i];

    targetObj[primaryKey] = logId;
    targetArr.push(targetObj);
  }

  return await model.deleteAll(targetArr);
}

exports.handler = async (event, context, callback) => {
  var ORM = require('node-dynamodb-orm');
  var DynamoDBORM = ORM.DynamoDBORM;

  DynamoDBORM.updateConfig({
    region          : process.env['AWS_DYNAMO_DB_REGION'],
    accessKeyId     : process.env['AWS_PUBLIC_KEY'],
    secretAccessKey : process.env['AWS_SECRET_KEY']
  });

  var model = new DynamoDBORM(process.env['AWS_DYNAMO_DB_MY_TABLE_NAME']);

  var arrStr = await getAll(model);
  await deleteAll(arrStr, model);
}
